services:
  - type: web
    name: user-management-system-api
    env: node
    buildCommand: chmod +x install-backend.sh && ./install-backend.sh
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
  
  - type: web
    name: user-management-system
    env: static
    buildCommand: chmod +x install.sh && ./install.sh
    staticPublishPath: ./Frontend/dist/user-management-system/browser
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: BACKEND_URL
        fromService:
          name: user-management-system-api
          type: web
          property: host 
