services:
  - type: web
    name: user-management-system
    env: static
    buildCommand: chmod +x install.sh && ./install.sh
    staticPublishPath: ./Frontend/dist/user-management-system/browser
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 
